// <auto-generated />
using System;
using EmployeeTask.AccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeTask.AccountService.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("GovernorateID")
                        .HasColumnType("int");

                    b.HasKey("AreaID");

                    b.HasIndex("GovernorateID")
                        .IsUnique()
                        .HasFilter("[GovernorateID] IS NOT NULL");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.District", b =>
                {
                    b.Property<int>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictID"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("DistrictID");

                    b.HasIndex("AreaID")
                        .IsUnique()
                        .HasFilter("[AreaID] IS NOT NULL");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("AddressID")
                        .IsUnique()
                        .HasFilter("[AddressID] IS NOT NULL");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Governorate", b =>
                {
                    b.Property<int>("GovernorateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernorateID"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("GovernorateID");

                    b.ToTable("Governorates", (string)null);
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Area", b =>
                {
                    b.HasOne("EmployeeTask.AccountService.Entities.Governorate", "Governorate")
                        .WithOne()
                        .HasForeignKey("EmployeeTask.AccountService.Entities.Area", "GovernorateID");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.District", b =>
                {
                    b.HasOne("EmployeeTask.AccountService.Entities.Area", "Area")
                        .WithOne()
                        .HasForeignKey("EmployeeTask.AccountService.Entities.District", "AreaID");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("EmployeeTask.AccountService.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeTask.AccountService.Entities.Address", "Address")
                        .WithOne()
                        .HasForeignKey("EmployeeTask.AccountService.Entities.Employee", "AddressID");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
